# Generated by Django 5.1.4 on 2024-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_peoples'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='user_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
