# Generated by Django 5.1.4 on 2024-12-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_peoples_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'employee'), ('MANAGER', 'manager')], default='emp', max_length=10),
        ),
    ]
